baseurl = "https://asimumba.rbind.io/"
title = "R . Data Science . Business Intelligence"
canonifyurls = true
theme = "anatole"
languageCode = "en"
DefaultContentLanguage = "en"

disqusShortname = "asimumba"
googleAnalytics = "G-251788376"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]


[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80