project:
  type: website

website:
  title: "R . Data Science . Business Intelligence"
  site-url: https://asimumba.rbind.io/
  repo-url: https://github.com/rbind/asimumba.web/
  google-analytics: "G-BJDLEWB0XZ"
  repo-actions: [edit, issue]
  comments:
    utterances:
      repo: rbind/asimumba.web
      label: "Comments"
      theme: github-light
  open-graph: true
  twitter-card:
    creator: "@asimumba_"
    card-style: summary_large_image
  favicon: /data/favicon.ico
  navbar:
    right:
      - blog.qmd
      - Accomplishments.qmd
      - icon: github
        href: https://github.com/asimumba/
      - icon: twitter
        href: https://twitter.com/asimumba_/
      - icon: stack-overflow
        href: https://stackoverflow.com/users/8137815/aaron-simumba/
  page-footer:
    left: "© 2022 Aaron Simumba. Powered by [Quarto](https://quarto.org/) and [Netflify](https://www.netlify.com/). License: [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
    right:
      - icon: github
        href: https://github.com/asimumba/
      - icon: twitter
        href: https://twitter.com/asimumba_/
      - icon: envelope
        href: mailto:simumbaaaron20@gmail.com
citation: true
toc: true
format:
  html:
    theme: 
      dark: darkly
    css: styles.css
    



