# Site settings
baseURL = "https://asimumba.rbind.io/"
languageCode = "en-US"
title = "Data Science. R. Stock Markets"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-101235795-1"

# Copyright
copyright = "&copy;2020 Aaron Simumba"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[params]

  # Metadata for search engines and social sharing
  author = "Aaron Simumba"
  description = ""
  shareImage = "images/social.jpg"
  twitterHandle = "asimumba_"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      #youtubeId = "UCpeLQRVt3O0kdecIrQpDibg"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "https://zedr.rbind.io/"

      [[params.links.list1.link]]
        text = "Email"
        url = "simumbaa21@gmail.com"
        
    
      [[params.links.list1.link]]
        text = "Github"
        url = "https://github.com/asimumba"
        
      [[params.links.list1.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/aaronsimumba/"
        
    # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Projects"

      [[params.links.list3.link]]
        text = "Data-Driven Entrepreneurship Viz"
        url = "https://bongohive.co.zm/data-driven-entrepreneurship/"

      [[params.links.list3.link]]
        text = "African Stock Markets"
        url = "https://zedr.rbind.io/2018/11/07/african-markets-indices-tracker/"

      [[params.links.list3.link]]
        text = "Data Extraction"
        url = "https://zedr.rbind.io/2017/10/12/breathing-life-back-into-pdf-presented-data/"


  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/asimumba_"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/zedsamurai/?hl=en"


  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
