BaseUrl= "https://asimumba.rbind.io/"
LanguageCode= "en-US"
Title= "Aaron Simumba"
paginate = 3
DisqusShortname = "asimumba"
Copyright = "All rights reserved 2017"
canonifyurls = false
enableEmoji = true 

footnotereturnlinkcontents = "↩"

[permalinks]
  post = "/:year/:month/:day/:slug"
  
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[menu.main]]
  name = "About me"
  weight = -90
  identifier = "about"
  url = "/about"

[[menu.main]]
  name = "Blog"
  weight = -100
  identifier = "blog"
  url = "/"
  
[[menu.main]]
  name = "CV"
  weight = -110
  identifier = "cv"
  url = "/cv"
  
[[menu.main]]
  name = "Projects"
  weight = -120
  identifier = "projects"
  url = "/projects"
  
  
[params]
  description = "Welcome to my website"
  metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
  cover = "images/cover.jpg"
  author = "Aaron Simumba"
  authorlocation = "Lusaka, Zambia"
  authorwebsite = "https://asimumba.rbind.io/"
  authorbio= "Tech crazy, society explorer,lost in the Data science dungeon"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-101235795-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "asimumba"
  twitterName = "zedsamurai"
  facebookName = "aaron.s.simumba"
  linkedinName = "aaron-simumba-13737958"
  stackoverflowName = "aaron-simumba-8137815"
  email = "mailto:simumbaa21@gmail.com"
  
  
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"
  
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex", "sql", "python"]
  highlightjsTheme = "github"


  [params.social]
    twitter = "zedsamurai"
    github = "asimumba"
    