# Site settings
baseURL = "https://asimumba.rbind.io/"
languageCode = "en-us"
title = "Aaron Simumba"
theme = "hugo-freelancer-theme"
enableEmoji = "true"
googleAnalytics = "UA-101235795-1"
disqusShortname = "asimumba"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Aaron Simumba"
    description = "R - Stock Markets - Data Science"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "simumbaa21@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Data Science portfolio"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "avatar.png"
        name = "Hi, I'm Aaron"
        subtitle = "R - Data Science - Stock Markets"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "Currently working in the financial services sector, and previously I was a Data Management Associate at [mPharma](//www.mpharma.com/). In another life, I am an Accounting and Finance major. Graduated from the University of Namibia with a BA degree in Accounting(Honours). Previously tutored Business Administration students in the art of business and accounting at the University of Zambia. I am lost in the Data Science web… hoping to find my way out of the maze soon. I find data and the process of data analysis to glean insight from the raw data, overly exciting and fascinating alike. In addition, I’m fascinated by stock markets and everything with a business and finance buzz. I can be found on [Github](//github.com/asimumba) poking around interesting projects… and occasionally I rant on [Twitter](//twitter.com/asimumba_)."
        right = ""
        
        [params.about.button]
            text = "Blog"
            link = "//zedr.rbind.io/"
            icon = "blog"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "(c) Aaron Simumba powered by [blogdown](//github.com/rstudio/blogdown) and [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            #Postal address (add as many lines as necessary)
            address = ["Lusaka, Zambia"]

        [params.footer.social]
            title = "Connect with me"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/asimumba"

            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "//twitter.com/asimumba_"
            
            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "//linkedin.com/aaronsimumba"

        [params.footer.credits]
           title = "Data Musings"
           text = "[Blog](//zedr.rbind.io/)"
