baseurl = "https://asimumba.rbind.io/"
title = "Data Science . R . Business Intelligence"
copyright = "Copyright &copy; 2022 - Aaron Simumba"
canonifyurls = true
theme = "hugo-kiera"
disqusShortname = "asimumba"
googleAnalytics = "UA-101235795-2"
enableEmoji = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
paginate = 20

[permalinks]
    post = "/:year/:month/:day/:slug/"

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = false

[author]
    name = "Aaron Simumba"
    github = "asimumba"
    linkedin = "aaronsimumba"
    twitter = "asimumba_"
    email = "simumbaaaron20@gmail.com"

[params]
    tagline = "A Data Connoisseur's playground - Where data mets ideas"
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "css"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    favicon = "favicon.ico"


[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
    
[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
