baseurl = "https://asimumba.rbind.io/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Aaron Simumba"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentsCodeFences = true
disqusShortname = "asimumba"
googleAnalytics = "UA-101235795-1"

[Params]
  subtitle = "Aspiring Data Scientist & Blogger | R & Stock Markets Enthusiast"
  #logo = "img/avatar.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
  
#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  #name = "Aaron Simumba"
  website = "https://asimumba.rbind.io/"
  email = "simumbaa21@gmail.com"
  facebook = "aaron.s.simumba"
  googleplus = "+aaronsimumba" # or xxxxxxxxxxxxxxxxxxxxx
  github = "asimumba"
  #gitlab = "username"
  twitter = "zedsamurai"
  #reddit = "username"
  linkedin = "aaron-simumba"
  #xing = "username"
  stackoverflow = "users/8137815/aaron-simumba"
  #snapchat = "username"
  #instagram = "username"
  youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2
    
[[menu.main]]
    name = "CV"
    url = "cv/2017-09-22-curriculum-vitae"
    weight = 3
    
[[menu.main]]
    name = "Projects"
    url = "projects/projects"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 5

