baseURL = "https://asimumba.rbind.io"
languageCode = "en-us"
title = "Aaron Simumba - R . Data Science . Stock Markets"
theme = "forty"
enableEmoji = "true"
googleAnalytics = "UA-101235795-1"
disqusShortname = "asimumba"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  name = "Aaron Simumba"
  description = "Former Data Management Associate - mPharma"

  # Link custom assets relative to /static
  #custom_css = []
  #custom_js  = []
  favicon = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  [permalinks]
    post = "/:year/:month/:day/:slug/"

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Data Musing"
    subtitle = "Data Science Portfolio"
    #menu = "Menu"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blog"
      url = "https://zedr.rbind.io/"

    [[params.navigation.links]]
      name = "CV"
      url = "https://asimumba.github.io/online-cv/"

    [[params.navigation.links]]
      name = "About"
      url = "https://zedr.rbind.io/about/about/"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

  # Banner section
  [params.banner]
    title = "Hi, I'm Aaron"
    subtitle = "Aspiring Data Scientist & Blogger | R & Stock Markets Enthusiast\n | \n Data Visualisation, SQL, Python, Tableau, and Microsoft Power BI."

  # Tiles Section
  [params.tiles]
    enable = true
    [[params.tiles.showcase]]
      title = "Data Driven Entrepreneurship Pursuits"
      subtitle = "Sector Visualizations"
      image = "ddep.png"
      url = "https://bongohive.co.zm/data-driven-entrepreneurship/#1512737748557-24a47327-b1c0"

    [[params.tiles.showcase]]
      title = "Deploying Metabase through Heroku"
      subtitle = "Powering Business Intelligence"
      image = "metabase.png"
      url = "https://zedr.rbind.io/2018/12/26/deploying-metabase-through-heroku-app/"

    [[params.tiles.showcase]]
      title = "Data Science Africa"
      subtitle = "Data Science reference material"
      image = "laptop.jpg"
      url = "https://github.com/asimumba/Data-Science-material"

    [[params.tiles.showcase]]
      title = "Mapping Twitter Data"
      subtitle = "Followers/following interactions"
      image = "twitter.png"
      url = "https://zedr.rbind.io/2017/10/02/mapping-twitter-followers-and-following-in-r/"

    [[params.tiles.showcase]]
      title = "Internet Penetration in Zambia"
      subtitle = "Data on internet and mobile usage"
      image = "int.jpg"
      url = "https://zedr.rbind.io/2017/09/27/mobile-internet-penetration-in-zambia/"

    [[params.tiles.showcase]]
      title = "#DataHack4FI Twitter Data"
      subtitle = "Mining #datahack4fi data with Google Data Studio"
      image = "datahack.png"
      url = "https://zedr.rbind.io/2018/11/11/datahack4fi-twitter-data/"
      
   [[params.tiles.showcase]]
      title = "African Stock Markets Indices Tracker"
      subtitle = ""
      image = "indices.png"
      url = "https://zedr.rbind.io/2018/11/07/african-markets-indices-tracker/"

    [[params.tiles.showcase]]
      title = "What is in the numbers: A Look at the Lusaka Securities Exchange"
      subtitle = "LASI yearly performance"
      image = "lasi.jpg"
      url = "https://zedr.rbind.io/2017/04/06/lusaka-stock-exchange/"

    [[params.tiles.showcase]]
      title = "Stocks Portfolio Analysis"
      subtitle = ""
      image = "stock.jpg"
      url = "https://zedr.rbind.io/2017/03/17/portfolio-analysis/"

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Footer sectionT
  [params.footer]
    enable = true
    copyright = "Aaron Simumba 2017 - 2019"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/asimumba_"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/aaron.s.simumba"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/asimumba"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/aaronsimumba"
      label = "LinkedIn"
