baseurl = "https://zedr.rbind.io/"
title = "Kiera"
copyright = "Copyright &copy; 2017 - ZedR"
canonifyurls = true
theme = "hugo-kiera"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = false

[author]
    name = "Aaron Simumba"
    github = "asimumba"
    gitlab = "asimumba"
    linkedin = "aaronsimumba"
    facebook = ""
    twitter = "asimumba21"
    instagram = ""

[params]
    tagline = "A Data Science Blog"


