baseurl = "https://asimumba.rbind.io/"
DefaultContentLanguage = "en"
title = "Aaron Simumba"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentsCodeFences = false
disqusShortname = "asimumba"
googleAnalytics = "UA-101235795-1"

[Params]
  subtitle = "Aspiring Data Scientist & Blogger | R & Stock Markets Enthusiast \ Data Visualisation, R programming, Python, Tableau, Microsoft Power BI and, Travelling and Gym."
  #logo = "img/avatar.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = false
  UseChroma = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex", "python"]
  highlightjsTheme = "github"
  
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[Params.bigimg]]
  src = "img/banner.jpg"
  desc = "Banner"
  position = "center top"
  
[[Params.bigimg]]
  src = "img/background.jpg"
  desc = "background"
  position = "center top"
  
[[Params.bigimg]]
  src = "img/triangle.jpg"
  desc = "Triangle"
  
[[Params.bigimg]]
  src = "img/sphere.jpg"
  desc = "Sphere"
  # position: see values of CSS background-position.
  position = "center top"
  
[[Params.bigimg]]
  src = "img/hexagon.jpg"
  desc = "Hexagon"
  
[[Params.bigimg]]
  src = "img/path.jpg"
  desc = "Beautiful Road"
  
[Author]
  #name = "Aaron Simumba "
  website = "https://asimumba.rbind.io/"
  email = "simumbaa21@gmail.com"
  linkedin = "aaronsimumba"
  github = "asimumba"
  stackoverflow = "users/8137815/aaron-simumba"
  twitter = "asimumba21"
  facebook = "aaron.s.simumba"
  googleplus = "+aaronsimumba" # or xxxxxxxxxxxxxxxxxxxxx
  youtube = "user/aaronsimumba"
  instagram = "zed_samurai"
  #gitlab = "username"
  #reddit = "username"
  #xing = "username"
  #snapchat = "username"
   # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1
    
[[menu.main]]
    name = "Blog"
    url = ""
    weight = 2
    
[[menu.main]]
    name = "CV"
    url = "cv/2017-09-22-curriculum-vitae"
    weight = 3
    
[[menu.main]]
    name = "Projects"
    url = "projects/projects"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 5

