baseurl = "https://zedr.rbind.io/"
title = "ZedR Blog - Data Science . R . Stock Markets"
copyright = "Copyright &copy; 2017 - 2018 - ZedR"
canonifyurls = true
theme = "hugo-kiera"
disqusShortname = "asimumba"
googleAnalytics = "UA-101235795-2"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 20

[permalinks]
    post = "/:year/:month/:day/:slug/"

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = false

[author]
    name = "Aaron Simumba"
    github = "asimumba"
    gitlab = "asimumba"
    linkedin = "aaronsimumba"
    facebook = ""
    twitter = "asimumba21"
    instagram = ""
    email = "simumbaa21@gmail.com"

[params]
    tagline = "A Data Science Blog"
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "css"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

[[menu.main]]
    name = "Portfolio"
    url = "https://asimumba.rbind.io/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
