baseurl = "https://zedr.rbind.io/"
title = "ZedR Blog"
copyright = "Copyright &copy; 2017 - ZedR"
canonifyurls = true
theme = "hugo-kiera"
disqusShortname = "asimumba"


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = false

[author]
    name = "Aaron Simumba"
    github = "asimumba"
    gitlab = "asimumba"
    linkedin = "aaronsimumba"
    facebook = ""
    twitter = "asimumba21"
    instagram = ""
    email = "simumbaa21@gmail.com"

[params]
    tagline = "A Data Science Blog"

[[menu.main]]
    name = "Main Site"
    url = "https://asimumba.rbind.io/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "https://asimumba.rbind.io/about/about/"
    weight = 2
