# Site settings
baseurl = "https://asimumba.rbind.io/"
languageCode = "en-us"
title = "Aaron Simumba"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-101235795-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "asimumba"

paginate = 10
footnotereturnlinkcontents = "↩"

[permalinks]
  post = "/:year/:month/:day/:slug"
  
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	name = "Aaron Simumba"
	description = "Tech crazy, society explorer,lost in the Data science dungeon"
	bio = "Aspiring Data Scientist & Blogger"
	# Enter optionally your twitter account
	twitter = "zedsamurai"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = ["js/center-img.js"]

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = "RSS"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Aspiring Data Scientist & Blogger"
	tweet = ""
	share = "Facebook"
	# 404 page
	title404 = ""
	subtitle404 = ""
	githubRepo = "https://github.com/rbind/asimumba"
	#gitter = "rbind/asimumba"
	

# options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex", "sql", "python"]
  highlightjsTheme = "github"


# Add additional social link entries underneath

[social]
    github = "https://www.github.com/asimumba"
    stackoverflow = "https://www.stackoverflow.com/8137815/aaron-simumba"
    linkedin = "https://www.linkedin.com/aaron-simumba-13737958"
    email = "mailto:simumbaa21@gmail.com"
    twitter  = "https://www.twitter.com/zedsamurai"
    facebook = "https://www.facebook.com/aaron.s.simumba"
    